config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  get 'rooms/index', to: 'rooms#index'
  get 'rooms/show',  to: 'rooms#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  mount_uploader :picture, PictureUploader
  default_scope  { order(created_at: :desc) }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room_id = params[:room_id].to_i
    @messages = Message.where(room_id: @room_id)
  end

  def index
    @room_ids = Message.select(:room_id).distinct.pluck(:room_id).sort
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AcTest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/messages/_message.html.slim
.message
  p
    = message.content
    - if message.picture?
      = image_tag message.picture.url

app/views/rooms/index.html.slim
h1
  | Chat Room List

ul
  - @room_ids.each do |room_id|
    li
      = link_to room_id, rooms_show_path(room_id: room_id)

app/views/rooms/show.html.slim
h1
  | Chat Room #{@room_id}

form id="test_form" data-form="" data-room-id="#{@room_id}"
  input type="text" data-content=""
  input type="file" data-picture=""
  input type="submit" data-send=""

#messages
  - if @messages.present?
    = render @messages

coffee:
  # app/assets/javascripts/channels/room.coffeeで登録したカスタムイベントの
  # channel_room_create_subscriptionsをキックしている。
  $(document).trigger("channels_room_create_subscriptions")